// SPDX-License-Identifier: MIT
// BUILD-PROOF: GEN_TEMPLATE_ARTIFACT_V1 — writes public/artifacts/payments.json,
// the pinned template artifact the console's launch rail fetches.
//
// WHY A SCRIPT AND NOT A BUILD STEP READING out/. The forge artifact's
// `bytecode.object` is NOT byte-identical to Solidity's `type(X).creationCode`
// under this project's settings (via_ir), and a stale `out/` silently produces
// a different blob again. Both failure modes ship an artifact whose hash does
// not match what the factory pinned — at which point the rail correctly refuses
// to enable and it looks like a bug.
//
// So the artifact is generated from the SAME EXPRESSION the factory hashes and
// the console must send: type(PossessioPayments).creationCode. One source of
// truth, no transcription step.
//
// The script ASSERTS the result against the live factory's pin before writing.
// If PossessioPayments.sol changes, this refuses to write rather than emitting
// an artifact that would brick the launch rail.
//
// RUN:
//   forge script script/GenTemplateArtifact.s.sol
//
// Re-run after any change to PossessioPayments.sol or its imports — and expect
// it to REVERT, because the live factory's pin is immutable.

pragma solidity ^0.8.26;

import "forge-std/Script.sol";
import {PossessioPayments} from "../src/PossessioPayments.sol";

contract GenTemplateArtifact is Script {
    /// @notice The pinned value inside PossessioFactory on Base 8453. Immutable.
    bytes32 constant LIVE_FACTORY_PIN =
        0x14357940f7396034c9139e740ca408c53ff33bf8d52f8a8a93e337bffb9ee39d;
    address constant FACTORY = 0x0DD06656cb9a38730a7177792C357E48cEdb49Bd;

    error TemplateDrift(bytes32 computed, bytes32 pinned);

    function run() external {
        bytes memory cc = type(PossessioPayments).creationCode;
        bytes32 hash = keccak256(cc);

        // The whole point. A drifted template must not be published.
        if (hash != LIVE_FACTORY_PIN) revert TemplateDrift(hash, LIVE_FACTORY_PIN);

        string memory json = string.concat(
            '{"name":"PossessioPayments",',
            '"chainId":8453,',
            '"factory":"', vm.toString(FACTORY), '",',
            '"templateCodehash":"', vm.toString(hash), '",',
            '"note":"Creation code for the Account template pinned by PossessioFactory on Base 8453. ',
            'The launch rail hashes this and compares it to factory.templateCodehash() read live from ',
            'chain. A mismatch keeps the rail in preview and deploys nothing. Generated by ',
            'script/GenTemplateArtifact.s.sol from type(PossessioPayments).creationCode - never ',
            'transcribed, never read from a stale out/ artifact.",',
            '"creationCode":"', vm.toString(cc), '"}'
        );

        vm.writeFile("public/artifacts/payments.json", json);

        console2.log("=== template artifact written ===");
        console2.log("  public/artifacts/payments.json");
        console2.log("  creation code bytes:", cc.length);
        console2.log("  codehash (matches the live factory pin):");
        console2.logBytes32(hash);
    }
}
